print("Welcome to the tip calculator")
total_bill=float(input("What was the total bill? $"))
tip=int(input("How much tip would you like to give? 10,12 0r 15?"))
split=int(input("Jow many people to split the bill?"))
pay=total_bill*(1+tip/100)
print(f"Each person shoulf pay:{round(pay/split,2)}")